const TimelineConstants = {
	REQUEST_TIMELINES: 'REQUEST_TIMELINES',
	FETCH_TIMELINES: 'FETCH_TIMELINES',
	RECEIVE_TIMELINES: 'RECEIVE_TIMELINES',

	REQUEST_TIMELINE: 'REQUEST_TIMELINE',
	FETCH_TIMELINE: 'FETCH_TIMELINE',
	RECEIVE_TIMELINE: 'RECEIVE_TIMELINE',

	UPDATE_TIMELINE: 'UPDATE_TIMELINE',

	DELETE_TIMELINE: 'DELETE_TIMELINE'
}

module.exports = TimelineConstants
